#应用名称
spring:
  application:
    name: client

#端口号
server:
  port: 8804
  #设置随机端口号，0表示随机
#  port: 0

#服务注册中心
eureka:
  instance:
    #续约到期时间,心跳检查
    lease-expiration-duration-in-seconds: 90
    #续约更新时间
    lease-renewal-interval-in-seconds: 30
    #向注册中心注册显示的实例名称，默认取应用名称，如果名称和端口号都相同，会造成冲突
    #1.不同应用服务设置不同名称来区分
    #2.相同应用服务设置不同端口号来区分
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #配置开启监控功能
    healthcheck:
      enable: true
    serviceUrl:
      #指向服务注册中心的地址，如果是注册中心集群，写一个注册中心的地址即可，他们会互相同步
      defaultZone: http://server2:8802/eureka/

